function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  X9:  vector of x data
%  Y9:  vector of y data
%  X10:  vector of x data
%  Y10:  vector of y data
%  X11:  vector of x data
%  Y11:  vector of y data
%  X12:  vector of x data
%  Y12:  vector of y data
%  X13:  vector of x data
%  Y13:  vector of y data
%  X14:  vector of x data
%  Y14:  vector of y data
%  X15:  vector of x data
%  Y15:  vector of y data
%  X16:  vector of x data
%  Y16:  vector of y data
%  X17:  vector of x data
%  Y17:  vector of y data
%  X18:  vector of x data
%  Y18:  vector of y data
%  X19:  vector of x data
%  Y19:  vector of y data
%  X20:  vector of x data
%  Y20:  vector of y data
%  X21:  vector of x data
%  Y21:  vector of y data

%  Auto-generated by MATLAB on 11-Dec-2018 15:12:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create plot
plot(X2,Y2);

% Create plot
plot(X3,Y3);

% Create plot
plot(X4,Y4);

% Create plot
plot(X5,Y5);

% Create plot
plot(X6,Y6);

% Create plot
plot(X7,Y7);

% Create plot
plot(X8,Y8);

% Create plot
plot(X9,Y9);

% Create plot
plot(X10,Y10);

% Create plot
plot(X11,Y11);

% Create plot
plot(X12,Y12);

% Create plot
plot(X13,Y13);

% Create plot
plot(X14,Y14);

% Create plot
plot(X15,Y15);

% Create plot
plot(X16,Y16);

% Create plot
plot(X17,Y17);

% Create plot
plot(X18,Y18);

% Create plot
plot(X19,Y19);

% Create plot
plot(X20,Y20);

% Create plot
plot(X21,Y21);

% Create xlabel
xlabel('Time');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[1e-06 2.5e-05]);
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorGrid','on','YGrid','on','YMinorGrid','on');
