function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-Dec-2018 15:27:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','Ideal Buffer (Vin)');
set(plot1(2),'DisplayName','R = 3M');
set(plot1(3),'DisplayName','R = 750K');
set(plot1(4),'DisplayName','R = 187.5K');
set(plot1(5),'DisplayName','R = 46.875K');

% Create xlabel
xlabel('Input Voltage (V)');

% Create title
title('Source Follower - Vout vs Vin - M1 40u/0.8, M2 5u/10u Vb = 1.2V');

% Create ylabel
ylabel('Output Voltage (V)');

% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorGrid','on','YGrid','on','YMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.667437974180125 0.130848689627758 0.226872246696035 0.190919674039581],...
    'FontSize',12);

