T_IN = (0:0.01:1)' * 1E-6;

V_CHANGE_0_05uA_v2 = importfile("H:\FYP\Current source investigations\0_05uA_v2.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_05uA_v2 = V_CHANGE_0_05uA_v2(:,2)';    %get rid of first column

V_CHANGE_0_1uA = importfile("H:\FYP\Current source investigations\0_1uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_1uA = V_CHANGE_0_1uA(:,2)';    %get rid of first column

V_CHANGE_0_1uA_v2 = importfile("H:\FYP\Current source investigations\0_1uA_v2.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_1uA_v2 = V_CHANGE_0_1uA_v2(:,2)';    %get rid of first column

V_CHANGE_0_1uA_v3 = importfile("H:\FYP\Current source investigations\0_1uA_v3.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_1uA_v3 = V_CHANGE_0_1uA_v3(:,2)';    %get rid of first column

V_CHANGE_0_2uA = importfile("H:\FYP\Current source investigations\0_2uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_2uA = V_CHANGE_0_2uA(:,2)';    %get rid of first column

V_CHANGE_0_5uA = importfile("H:\FYP\Current source investigations\0_5uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_0_5uA = V_CHANGE_0_5uA(:,2)';    %get rid of first column

V_CHANGE_1_0uA = importfile("H:\FYP\Current source investigations\1_0uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_1_0uA = V_CHANGE_1_0uA(:,2)';    %get rid of first column

V_CHANGE_2_0uA = importfile("H:\FYP\Current source investigations\2_0uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_2_0uA = V_CHANGE_2_0uA(:,2)';    %get rid of first column

V_CHANGE_5_0uA = importfile("H:\FYP\Current source investigations\5_0uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_5_0uA = V_CHANGE_5_0uA(:,2)';    %get rid of first column

V_CHANGE_10_0uA = importfile("H:\FYP\Current source investigations\10_0uA.csv", [2, Inf]); %import the data from a file called results. Autogenerated
V_CHANGE_10_0uA = V_CHANGE_10_0uA(:,2)';    %get rid of first column

V_CHANGE_0_05uA_v2 = V_CHANGE_0_05uA_v2';
V_CHANGE_0_1uA = V_CHANGE_0_1uA';
V_CHANGE_0_1uA_v2 = V_CHANGE_0_1uA_v2';
V_CHANGE_0_1uA_v3 = V_CHANGE_0_1uA_v3';
V_CHANGE_0_2uA = V_CHANGE_0_2uA';
V_CHANGE_0_5uA = V_CHANGE_0_5uA';
V_CHANGE_1_0uA = V_CHANGE_1_0uA';
V_CHANGE_2_0uA = V_CHANGE_2_0uA';
V_CHANGE_10_0uA = V_CHANGE_10_0uA';



hold on;

%scatter(T_IN, V_CHANGE_0_05uA_v2);
scatter(T_IN, V_CHANGE_0_1uA);
scatter(T_IN, V_CHANGE_0_1uA_v2);
%scatter(T_IN, V_CHANGE_0_1uA_v3);


% scatter(T_IN, V_CHANGE_0_2uA);
% scatter(T_IN, V_CHANGE_0_5uA);
% scatter(T_IN, V_CHANGE_1_0uA);
% scatter(T_IN, V_CHANGE_2_0uA);
% scatter(T_IN, V_CHANGE_5_0uA);
% scatter(T_IN, V_CHANGE_10_0uA);
xlabel('Input pulse length uS');
ylabel('V_{CHANGE} V');


max_T_IN_index = [101,101,101,101,101,101,101]; %index 101
max_T_IN = T_IN(101);
min_T_IN_index = [61,31,15,9,5,5,5]; %61

for i = 1:1:7
    T_change(i) = T_IN(max_T_IN_index(i)) - T_IN(min_T_IN_index(i));
end


max_v_change = [V_CHANGE_0_1uA(101),V_CHANGE_0_2uA(101),V_CHANGE_0_5uA(101), V_CHANGE_1_0uA(101), V_CHANGE_2_0uA(101), V_CHANGE_5_0uA(101), V_CHANGE_10_0uA(101)]  ;
min_v_change = [V_CHANGE_0_1uA(min_T_IN_index(1)),V_CHANGE_0_2uA(min_T_IN_index(2)),V_CHANGE_0_5uA(min_T_IN_index(3)), V_CHANGE_1_0uA(min_T_IN_index(4)), V_CHANGE_2_0uA(min_T_IN_index(5)), V_CHANGE_5_0uA(min_T_IN_index(6)), V_CHANGE_10_0uA(min_T_IN_index(7))]  ;
delta_v_change = max_v_change - min_v_change;

gradients = delta_v_change./T_change;
V_intercepts = max_v_change - (gradients*max_T_IN);
t_intercepts = -1*V_intercepts./gradients;
% 
V1 = gradients*max_T_IN + V_intercepts;
V0 = V_intercepts;
% 
% plot([0 max_T_IN], [V0(1) V1(1)]);     %0.1uA
% plot([0 max_T_IN], [V0(2) V1(2)]);     %0.2uA
% plot([0 max_T_IN], [V0(3) V1(3)]);     %0.5uA
% plot([0 max_T_IN], [V0(4) V1(4)]);     %1.0uA
% plot([0 max_T_IN], [V0(5) V1(5)]);     %1.0uA
% plot([0 max_T_IN], [V0(6) V1(6)]);     %1.0uA
% plot([0 max_T_IN], [V0(7) V1(7)]);     %1.0uA
%legend('0.05uA with buffer', '0.1uA','0.1uA with buffer','0.1uA v3', '0.2uA','0.5uA','1uA','2uA','5uA','10uA','0.1uA linear','0.2uA linear','0.5uA linear','1uA linear','2uA linear','5uA linear','10uA linear');

legend('0.1uA','0.1uA v2');

figure;

currents = [0.1,0.2,0.5,1,2,5,10] * 1E-6;
scatter(currents, t_intercepts);
set(gca,'xscale','log');
set(gca,'yscale','log');
xlabel('I_{REF} A');
ylabel('Onset delay S');

p = polyfit(log(currents),log(t_intercepts),1);
z = polyval(p,log(currents));
hold on;
plot(currents, exp(z));

title('I_{REF} vs Onset delay');




